### PR TITLE
MVP

### LINKED ISSUE #1: Default 501 response
Basically, just be able to accept a basic request from the client and respond with a 501 message. This does not need to care about the type of request, or the URI, or any details likes cookies of URI parameters. It simply needs to see the request was made, and send back a 404 to the client (it doesn't even need to be a 501 page)

### LINKED ISSUE #8: Use a template for the generic response pages
The likes of 404 and 501 pages are all basically the same, the only difference is that message we would want to put into them. We are also likely to want to tweak things, like footer messages. As such, there should be a generic template file that we can pass in the string to display as the error message.

### PR DESCRIPTION
**Pull request by nabijaczleweli**
MVP is done now and here's the rundown:

  * [x] subdir hosting
  * [x] symlinks not followed by default (`-s` switch to do so)
  * [x] root not required
  * [x] index generation for directories [1]
  * [x] lack of caching
  * [x] default hosted directory is current working dir
  * [x] default port is first free one from `8000` up to `9999` [2]
  * [x] response to unimplemented features (like a POST request) - 501 Not Implemented
  * [x] files are served with a correct MIME type
  * [x] generated responses use simple templating [3]
  * [x] implemented request methods: OPTIONS, GET, HEAD and TRACE
  * [ ] externally accessible URL is copied to clipboard at start (withdrawn under @thecoshman's recommendation due to compilation errors)
  * [x] proper handling of percent-encoded URLs (like `асдф fdsa`)

[1] Should we check if the dir contains an index file? If so -- what extensions should we support?
[2] A lot of people (some more reputable than @thecoshman) think this is a terrible idea and that we should use port `0` instead.
[3] If this is not good enough this shouldn't close 8

Closes #1
Closes #8

<sub>Note: do not merge this with a merge commit. Do an FF merge if you need to but better yet leave this to me and I'll do it cleanly.</sub>

### CODE REVIEW

**Comment by thecoshman** [comment]
regarding index generation, if the browser requests a page called `index.html` and there is one in the folder, then that should be returned. I think it is safe to presume that if that file does exist, that in the intention is to offer it. What we do for other file extensions, I'm not sure. I also don't think that it's something to worry about too much for now; we can decide better handling later.

Regarding default port, let's just stick with this for now. The behaviour currently seems to be 'ok' for the most part, the only debatable thing is the method to choosing one 'at random'. 

I think overall this is looking ok, but I just want to test it a bit first.

**Comment by nabijaczleweli** [comment]
Well, I was thinking about the following scenarios:

request | condition | returned
--------|------------|-------
`/` | none | directory listing for `/`
`/` | `/index.html` exists | `/index.html`
`/` | multiple `/index.XXX` files exist | ???

Currently we only ever return option one, but support for returning indices from requested directories would be nice, eh?

**Comment by thecoshman** [comment]
@nabijaczleweli I think for now, we'll just stick with what we have and think it out in a issue focused on it

**Comment by nabijaczleweli** [comment]
Right, then make an actual "approve" review and let's get cracking

**Comment by nabijaczleweli** [comment]
What did I tell you? To do a fast-forward merge. What did you do? made a non-fast-forward merge.

**Comment by thecoshman** [comment]
LOL I payed attention very good :D

**Pull request merged**
