### PR TITLE
Change BLKGETSIZE to c_int on musl target

### LINKED ISSUE #107: Build fails on musl host
When compiling https on `x86_64-unknown-linux-musl` build fails due a difference in the function signature of `ioctl`

```
$ rustc --version
rustc 1.43.1 (8d69840ab 2020-05-04)
```

```
$ cargo build
Compiling https v1.9.2 (/home/adrianisuru/http)
error[E0308]: mismatched types
  --> src/util/os/non_windows_non_macos.rs:39:47
   |
39 |             let ok = unsafe { ioctl(dev_file, BLKGETSIZE, &mut block_count as *mut c_ulong) } == 0;
   |                                               ^^^^^^^^^^ expected `i32`, found `u64`
   |
help: you can convert an `u64` to `i32` and panic if the converted value wouldn't fit
   |
39 |             let ok = unsafe { ioctl(dev_file, BLKGETSIZE.try_into().unwrap(), &mut block_count as *mut c_ulong) } == 0;
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
  --> src/util/os/non_windows_non_macos.rs:39:47
   |
39 |             let ok = unsafe { ioctl(dev_file, BLKGETSIZE, &mut block_count as *mut c_ulong) } == 0;
   |                                               ^^^^^^^^^^ expected `i32`, found `u64`
   |
help: you can convert an `u64` to `i32` and panic if the converted value wouldn't fit
   |
39 |             let ok = unsafe { ioctl(dev_file, BLKGETSIZE.try_into().unwrap(), &mut block_count as *mut c_ulong) } == 0;
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
For more information about this error, try `rustc --explain E0308`.
error: could not compile `https`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: could not compile `https`.
```
On `glibc` systems the `ioctl` function signature is 
```c
extern int ioctl (int __fd, unsigned long int __request, ...) __THROW;
```
but on `musl` systems the signature is
```c
int ioctl (int, int, ...);
```
so compiling [`src/util/os/non_windows_non_macos.rs`](https://github.com/thecoshman/http/blob/master/src/util/os/non_windows_non_macos.rs) fails because `BLKGETSIZE` is a `c_ulong` not a `c_int`

### PR DESCRIPTION
**Pull request by adrianisuru**
Fixes #107

### CODE REVIEW

**Comment by adrianisuru** [comment]
I believe the fail on appveyor and xenial nightly are unrelated.

**Comment by nabijaczleweli** [comment]
It took some doing, but I managed to get cargo building in an Alpine 3.11.6 chroot – `fs/linux.h` didn't exist for me by default there (packages.d.o says it's from `libc6-dev`), so I updated to `sys/mount.h`, which works on both musl and glibc.

In the meantime I've also cleaned up the patch a bit, and the new version runs fine for me in the chroot. Would you mind building and testing the updated PR?

**Comment by adrianisuru** [comment]
I'm running void linux musl. Everything builds fine. It also serves static
http/JavaScript/css fine in most cases. For some reason I'm still getting a
segfault when I try to serve files built with wasm-pack (that I don't get
on a glibc system) but that's a different issue.

**Comment by nabijaczleweli** [comment]
Void was also on the radar but Alpine's chroots were easier to get hold of for me; good to hear it (mostly) works there as well.

As for the segfaults – a stab in the dark, but does `-e`/`--no-encode` fix them?

**Comment by nabijaczleweli** [comment]
Thanks for the patch!

**Comment by adrianisuru** [comment]
`--no-encode` fixed it yes.
Thank you!

**Comment by adrianisuru** [comment]
`--no-encode` fixed it yes.
Thank you!

**Comment by nabijaczleweli** [comment]
Released in [`v1.9.3`](https://github.com/thecoshman/http/releases/tag/v1.9.3). Thanks again for your patches and testing!

**Pull request merged**
