### PR TITLE
TLS and temp dir removal

### LINKED ISSUE #40: Auto-generate self signed certificates
If certificates are not provided, but encryption requested, then self signed certifications should be generated and used automatically. Not sure if this is practical though.

### PR DESCRIPTION
**Pull request by nabijaczleweli**
TLS and temp dir removal are done now and here's the rundown:

  * [x] temporary directories are cleaned up after exiting
  * [x] TLS hosting support
  * [ ] no HTTP -> HTTPS redirection [1]
  * [x] on-demand one-off TLS identity autogeneration
  * [x] proper handling of files containing `#` and `%`
  * [x] symlink deletion now works as expected

[1] The way it's normally done is you get a redirect from a different port and we use just one.

<sub>Note: do not merge this with a merge commit. Do an FF merge if you need to but better yet leave this to me and I'll do it cleanly.</sub>

### CODE REVIEW

**Comment by thecoshman** [comment]
I accept that #40 is probably not that practical, but I still think that issue should remain open

**Comment by nabijaczleweli** [comment]
Alright then

**Comment by thecoshman** [comment]
Not a fan of the cli password handling. I think for most usages of this, cert files with no password wouldn't that unusual, so I'd try that by default. If it turns out the cert does require a password, I would then look for an env var or ask for user input. User input should allow for a password to be piped in for those who insist on having the password on the cli. Personally, I'd favour ask for password over using an env var.

**Comment by thecoshman** [comment]
I'm getting an error when I attempt to use the auto gen certs, a non zero return code apparently. There's no more info comming back than that

**Pull request merged**
